fix(cbor): remove const qualifiers
Remove const qualifiers on the input pointer of the
cbor functions. This is necessary because the zcbor
functions do not have a const qualifier and therefore
we get warnings such as:

src/cbor/edhoc_encode_message_2.c: In function
‘cbor_encode_m2_G_Y_CIPHERTEXT_2’:
src/cbor/edhoc_encode_message_2.c:48:59: error: cast
discards ‘const’ qualifier from pointer target type
 [-Werror=cast-qual]
   48 |         return zcbor_entry_function(payload,
payload_len, (void *)input, payload_len_out, states,
      |

Signed-off-by: Stefan Gloor <stefan.gloor@siemens.com>