chore(externals): bump zcbor to 788fa165 (0.9.1-dirty)
This commit gets rid of an unused variable, leading
to GCC warnings:

../../../externals/zcbor/src/zcbor_decode.c: In
function ‘zcbor_any_skip’:
../../../externals/zcbor/src/zcbor_decode.c:1461:17:
error: variable ‘additional’ set but not used
 [-Werror=unused-but-set-variable]
 1461 | uint8_t additional = ZCBOR_ADDITIONAL(*state->payload);
      | ^~~~~~~~~~

Signed-off-by: Stefan Gloor <stefan.gloor@siemens.com>