chore(ci): bump github actions
The current version is deprecated which leads to a failed pipeline:
Error: This request has been automatically failed because it uses
a deprecated version of `actions/upload-artifact: v3`.

Signed-off-by: Stefan Gloor <stefan.gloor@siemens.com>