chore: remove -Wpedantic
Remove -Wpendantic from main Makefile because it leads to
a warning in picolibc when compiling with Zephyr:

In file included from externals/mbedtls/include/mbedtls/platform_time.h:26,
                 from externals/mbedtls/include/mbedtls/platform_util.h:18,
                 from externals/mbedtls/include/mbedtls/cipher.h:22,
                 from externals/mbedtls/include/psa/crypto_builtin_primitives.h:88,
                 from externals/mbedtls/include/psa/crypto_driver_contexts_primitives.h:27,
                 from externals/mbedtls/include/psa/crypto_struct.h:68,
                 from externals/mbedtls/include/psa/crypto.h:71,
                 from src/edhoc/cert.c:29:
/home/runner/zephyrproject/zephyr/lib/libc/picolibc/include/time.h:30:2:
error: #include_next is a GCC extension [-Werror]
   30 | #include_next <time.h>
      |  ^~~~~~~~~~~~

This is hard to fix upstream and there seems to be no specific override
for the "is a GCC extension" warning.
Since we already use -Wall -Wextra we should catch the majority
of warnings. This seems to be a better tradeoff than removing -Werror.

Signed-off-by: Stefan Gloor <stefan.gloor@siemens.com>